In [134]:
# A simple way to maintain big data sets is to use CSV files (comma separated files).
# CSV files hold's up plain text and is a well know format that can be read by everyone including Pandas.

# Pandas is a Python library used for working with data sets. It hold's up method's for analyzing, and manipulating data.
import pandas  # Library
import os  # Module

# A module is a set of code or method's having .py extension.

cwd = os.getcwd()  # The os.getcwd() method return the current working / active directory in Python.

# To analyze the datatype of a variable in Python, we can use the built-in type() function.
# An inline function is one for which the compiler copy the code from the function definition directly, instead of creating a separate set of instructions in memory.
# The listdir() method is provided by the os module, and this method, return a list of identifier of all the files provided path.

datum_directory = os.path.join(cwd,os.listdir(cwd)[-1])  # join() method in Python join one or more path components intelligently.

pandas.read_csv(datum_directory + '\\Datum.csv')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [139]:
dataframe = pandas.read_csv(datum_directory + '\\Datum.csv')
dataframe.drop(labels='customerID',axis='columns',inplace=True)  # The drop() method removes the specified row or column

In [140]:
# Rudimentary Datum analysis

import numpy

# 1. SHAPE --> shape() method, returns a tuple, that indicates the dimensions of a Python object.
shape = numpy.shape(dataframe)  # Data point represent, a 21 dimensional vector in space
print(shape)

(7043, 20)

In [141]:
# 2. Metadata corresponding attribute --> Return, attribute metadata
metadata = dataframe.info()
print(metadata)

# Observation --> Mutate data type of 'TotalCharges' attribute

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
 19  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB
None

In [167]:
# Analyzing missing data --> categorical

dataframe['gender'].value_counts()  # Return a Series containing count of unique element's

dataframe['SeniorCitizen'].value_counts()  # Observation --> Unbalanced, data points

dataframe['Partner'].value_counts()

dataframe['Dependents'].value_counts()  # Observation --> Unbalanced, data points

dataframe['PhoneService'].value_counts()  # Observation --> Unbalanced, data points

dataframe['MultipleLines'].value_counts()  # Observation --> Unbalanced, data points

dataframe['InternetService'].value_counts()  # Observation --> Unbalanced, data points

dataframe['OnlineSecurity'].value_counts()  # Observation --> Unbalanced, data points

dataframe['OnlineBackup'].value_counts()  # Observation --> Unbalanced, data points

dataframe['DeviceProtection'].value_counts()  # Observation --> Unbalanced, data points

dataframe['TechSupport'].value_counts()  # Observation --> Unbalanced, data points

dataframe['StreamingTV'].value_counts()  # Observation --> Unbalanced, data points

dataframe['StreamingMovies'].value_counts()  # Observation --> Unbalanced, data points

dataframe['Contract'].value_counts()  # Observation --> Unbalanced, data points

dataframe['PaperlessBilling'].value_counts()  # Observation --> Unbalanced, data points

dataframe['PaymentMethod'].value_counts()  # Observation --> Unbalanced, data points

dataframe['Churn'].value_counts()

# Observation --> Unbalanced, dataset

No     5174
Yes    1869
Name: Churn, dtype: int64

In [51]:
# Datum mutation

# Datum translation
# The replace() method replaces the specified value with another specified value.

Partner = dataframe['Partner'].replace('Yes',1).replace('No',-1)
Gender = dataframe['gender'].replace('Male',1).replace('Female',-1)
Dependents = dataframe['Dependents'].replace('Yes',1).replace('No',-1)
Phone_Service = dataframe['PhoneService'].replace('Yes',1).replace('No',0)
Multiple_Lines = dataframe['MultipleLines'].replace('No phone service',0).replace('Yes',1).replace('No',-1)
Internet_Service = dataframe['InternetService'].replace('DSL',1).replace('Fiber optic',2)
Online_Security = dataframe['OnlineSecurity'].replace('Yes',1).replace('No',-1)
Device_Protection = dataframe['DeviceProtection'].replace('Yes',1).replace('No',-1)
Tech_Support = dataframe['TechSupport'].replace('Yes',1).replace('No',-1)
Streaming_TV = dataframe['StreamingTV'].replace('Yes',1).replace('No',-1)
Streaming_Movies = dataframe['StreamingMovies'].replace('Yes',1).replace('No',-1)
Contract = dataframe['Contract'].replace('Month-to-month',1).replace('One year',2)
Paperless_Billing = dataframe['PaperlessBilling'].replace('Yes',1).replace('No',-1)
Churn = dataframe['Churn'].replace('Yes',1).replace('No',-1)